### ISSUE TITLE
Renaming of Universal Object ga to __gaTracker breaks integration with Dialogtech/Ifbyphone

### ISSUE THREAD

**Issue by Optimized-Marketing** [awesomemotive/google-analytics-for-wordpress#349]
When ga was changed to __gaTracker Dialogtech/Ifbyphone was no longer able to collect adwords data from my website and send it into google anayltics correctly. 

There should be an option for this setting because there are some system that require the ga object and other systems that conflict with ga.

**Comment by galbaras** [comment]
Actually, it also breaks Ecommerce tracking in WP e-commerce. A possibly solution is to add the following line of JS somewhere:

`var ga = typeof ga === "undefined" && typeof __gaTracker !== "undefined" ? __gaTracker : ga;`

**Comment by galbaras** [comment]
Rather than choose one name, which is what a filter would do, why not use them both? Essentially, the code I proposed above can be inserted after the declaration of __gaTracker(), unless some setting is checked to prevent it.

Seems like this will cover more cases.

Come to think of it, maybe the setting should have 3 options: ga(), __gaTracker() and both.

If you think the filter is sufficient, has it been released? How can it be used?

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
