### ISSUE TITLE
[Feature Request] Label Per Internal Path

### ISSUE THREAD

**Issue by amboutwe** [awesomemotive/google-analytics-for-wordpress#426]
Currently, all internal paths are labeled the same 'outbound-article-LABEL'. Request to add a comma separated label list to match the comma separated internal path option. This would allow tracking different internal paths for different affiliate programs.

/out/ - outbound-article-aff
/recommends/ - outbound-article-aff2

![selection_133](https://cloud.githubusercontent.com/assets/8060612/9767750/fa5c1e66-56dc-11e5-919a-8c21aca3e314.png)

**Comment by rimshot212** [comment]
Hi amboutwe,

I am the one who submitted this idea. Thank you for considering it!

I would like to clarify what I was thinking as the comma separated implementation wouldn't work for many peoples' needs. Instead of trying to accomplish the separate labels in two fields using comma separations, it would be super useful and more flexible if a user could just add new form fields for each label s/he wants to create for a set of links.

For example; if I have three different labels I want to use but multiple different "internal links to track as outbound" for each label, it would be much easier to have separate fields for each instance of label and link creation. You could just have a "Add new" button that creates the two new fields for each new label and link. Make sense?

Please let me know if you have any questions, or if I can clarify anything above.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
