### ISSUE TITLE
Remove plugin version printing from HTML

### ISSUE THREAD

**Issue by ste93cry** [awesomemotive/google-analytics-for-wordpress#489]
Even though there are other methods to get the plugin versions (e.g. from the README file), I can't think any valid reason to print the exact version of this plugin in the HTML source code. Maybe a new filter or option could be added to prevent printing of this information, or even better you could simply stop printing the following lines:

```
<!-- This site uses the Google Analytics by MonsterInsights plugin vx.x.x - Using Analytics tracking - https://www.monsterinsights.com/ -->
<!-- / Google Analytics by MonsterInsights -->
```

If you really want to sponsor your plugin, the name is sufficient imho

**Comment by chriscct7** [comment]
Hi there,
We use this information dozens, maybe honestly even hundreds of times per day in support, which saves us a ton of time, and helps get the support to users as fast as possible. There's no real downside to doing this.

-Chris

**Comment by ste93cry** [comment]
>There's no real downside to doing this

The downside is that you're making life easier to bad people by printing the version of the plugin. There are better ways to ask the user for the version of the plugin they're running. But, as I said, at least you could add a filter, an option or an action to control the printing of this information. I see no real downside doing this

**Comment by chriscct7** [comment]
The version of the plugin is already exposed by WordPress in many places. Our enqueued JS files have the version number, as do the publicly browseable readmes. Additionally our CSS/JS files are unique to each version because of the minification method we employ. From a bad actor perspective, even if none of these are true, most of them just detect if a plugin is installed and try running the exploit anyways regardless of the version installed (because its cheaper/faster to do than parsing HTML).

There is a plugin if you want to remove this information available here: https://wordpress.org/plugins/remove-google-analytics-comments/ and most HTML minification features of caching plugins also strip the HTML of comments as well

**Comment by ste93cry** [comment]
>The version of the plugin is already exposed by WordPress in many places
>Our enqueued JS files have the version number, as do the publicly browseable readmes

Sure, I said this in the first post. This does not mean you should show it even more than necessary

>Revealing the specific software version of the server may allow the server machine to become more vulnerable to attacks against software that is known to contain security holes. Server implementers are encouraged to make this field a configurable option.

This is an extract from [RFC 2068](http://www.ietf.org/rfc/rfc2068.txt). Although it's talking about server implementers, I think the concept is the same. I absolutely agree with you that there are many other ways (currently) to get the plugin version and that attackers will anyway try running exploits regardeless of the installed version, but I don't see any reason to help them

>There is a plugin if you want to remove this information

I did not know it, thank you for linking it
